# Generated by Django 6.0.7 on 2026-08-01 17:36

from django.db import migrations, models


def renommer_role_vendeur(apps, schema_editor):
    CustomUser = apps.get_model("accounts", "CustomUser")
    CustomUser.objects.filter(role="VENDEUR").update(role="GÉRANT")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('CAISSIER', 'Caissier'), ('SERVEUR', 'Serveur'), ('CUISINIER', 'Cuisinier'), ('LIVREUR', 'Livreur'), ('GÉRANT', 'Gérant'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
        migrations.RunPython(renommer_role_vendeur, migrations.RunPython.noop),
    ]
