# Generated by Django 6.0.7 on 2026-08-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_renommer_role_vendeur_en_gerant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text="Restaurant auquel appartient l'utilisateur (vide pour la plateforme/superadmin)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='tenants.restaurant'),
        ),
    ]
