# Generated by Django 6.0.7 on 2026-08-04 16:31

import apps.tenants.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenants.uploads.upload_restaurant),
        ),
    ]
