# Generated by Django 6.0.7 on 2026-08-04 16:17

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_photogalerie_temoignage'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AlterModelOptions(
            name='photogalerie',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos galerie'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterModelOptions(
            name='temoignage',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Témoignage', 'verbose_name_plural': 'Témoignages'},
        ),
        migrations.AlterModelManagers(
            name='contactmessage',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='photogalerie',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reservation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='temoignage',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant propriétaire de cette ligne', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.restaurant'),
        ),
        migrations.AddField(
            model_name='photogalerie',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant propriétaire de cette ligne', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.restaurant'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant propriétaire de cette ligne', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.restaurant'),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant propriétaire de cette ligne', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.restaurant'),
        ),
    ]
