# Generated by Django 6.0.7 on 2026-08-04 16:31

import apps.tenants.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogalerie',
            name='image',
            field=models.ImageField(upload_to=apps.tenants.uploads.upload_restaurant),
        ),
    ]
