# Generated by Django 6.0.7 on 2026-08-04 16:17

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_mouvementstock'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'base_manager_name': 'all_objects', 'ordering': ['produit__nom']},
        ),
        migrations.AlterModelManagers(
            name='mouvementstock',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='stock',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant propriétaire de cette ligne', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.restaurant'),
        ),
        migrations.AddField(
            model_name='stock',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant propriétaire de cette ligne', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.restaurant'),
        ),
    ]
