# Generated by Django 6.0.7 on 2026-08-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('adresse', models.CharField(blank=True, default='', max_length=255)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('actif', models.BooleanField(default=True, help_text="Désactiver pour suspendre l'accès du restaurant (abonnement impayé, etc.)")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('abonnement_expire_le', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['nom'],
            },
        ),
    ]
