# Generated by Django 6.0.7 on 2026-08-05 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('prix_mensuel', models.IntegerField(default=0, help_text='Prix par mois (en FCFA)')),
                ('nb_utilisateurs_max', models.PositiveIntegerField(default=1)),
                ('nb_caisses_max', models.PositiveIntegerField(default=1)),
                ('modules', models.JSONField(default=list, help_text='Liste des modules autorisés : menu, commandes, caisse, stock, livraison, rapports, cuisine, multi_caisses...')),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='plan',
            field=models.ForeignKey(blank=True, help_text="Plan d'abonnement du restaurant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='tenants.plan'),
        ),
    ]
