# Generated by Django 6.0.7 on 2026-08-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_creer_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrePlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plateforme', models.CharField(default='RestaurantPro', max_length=100)),
                ('nom_beneficiaire', models.CharField(blank=True, default='', help_text='Nom affiché pour les paiements (ex: votre nom)', max_length=100)),
                ('telephone_paiement', models.CharField(blank=True, default='', help_text='Numéro Mobile Money / téléphone où les restaurants doivent payer', max_length=20)),
                ('instruction_paiement', models.TextField(blank=True, default='', help_text='Texte affiché au gérant pour payer (ex: envoyer le montant, puis nous prévenir)')),
            ],
            options={
                'verbose_name': 'Paramètres de la plateforme',
                'verbose_name_plural': 'Paramètres de la plateforme',
            },
        ),
    ]
