# Generated by Django 6.0.7 on 2026-08-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_parametreplateforme'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametreplateforme',
            name='cinetpay_active',
            field=models.BooleanField(default=False, help_text='Activer le paiement en ligne par CinetPay (Mobile Money).'),
        ),
        migrations.AddField(
            model_name='parametreplateforme',
            name='cinetpay_apikey',
            field=models.CharField(blank=True, default='', help_text='API key CinetPay (provient du panel CinetPay)', max_length=100),
        ),
        migrations.AddField(
            model_name='parametreplateforme',
            name='cinetpay_devise',
            field=models.CharField(blank=True, default='XOF', help_text="Devise des paiements (XOF pour l'Afrique de l'Ouest / Mali)", max_length=5),
        ),
        migrations.AddField(
            model_name='parametreplateforme',
            name='cinetpay_site_id',
            field=models.CharField(blank=True, default='', help_text='Site ID CinetPay', max_length=50),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Identifiant unique côté plateforme', max_length=100, unique=True)),
                ('cinetpay_transaction_id', models.CharField(blank=True, default='', help_text='ID renvoyé par CinetPay', max_length=100)),
                ('montant', models.PositiveIntegerField(default=0, help_text='Montant en FCFA')),
                ('devise', models.CharField(default='XOF', max_length=5)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SUCCES', 'Réussi'), ('ECHEC', 'Échoué'), ('ANNULE', 'Annulé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='tenants.restaurant')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
            },
        ),
    ]
