# Generated by Django 6.0.7 on 2026-08-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_parametreplateforme_cinetpay_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametreplateforme',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la plateforme (affiché dans la console)', null=True, upload_to='plateforme/logos'),
        ),
    ]
