# Generated by Django 6.0.7 on 2026-08-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_parametreplateforme_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametreplateforme',
            old_name='cinetpay_devise',
            new_name='paydunya_devise',
        ),
        migrations.RenameField(
            model_name='parametreplateforme',
            old_name='cinetpay_active',
            new_name='paydunya_active',
        ),
        migrations.RenameField(
            model_name='parametreplateforme',
            old_name='cinetpay_apikey',
            new_name='paydunya_master_key',
        ),
        migrations.RenameField(
            model_name='parametreplateforme',
            old_name='cinetpay_site_id',
            new_name='paydunya_private_key',
        ),
        migrations.RenameField(
            model_name='paiement',
            old_name='cinetpay_transaction_id',
            new_name='paydunya_token',
        ),
        migrations.AddField(
            model_name='parametreplateforme',
            name='paydunya_mode',
            field=models.CharField(blank=True, default='test', help_text='Mode de paiement : test (sandbox) ou live (production)', max_length=10),
        ),
        migrations.AddField(
            model_name='parametreplateforme',
            name='paydunya_token',
            field=models.CharField(blank=True, default='', help_text='Token PayDunya (application / AppDunya)', max_length=200),
        ),
    ]
