# Generated by Django 6.0.7 on 2026-08-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_rename_cinetpay_devise_parametreplateforme_paydunya_devise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='paydunya_token',
            field=models.CharField(blank=True, default='', help_text='Token de facture PayDunya', max_length=100),
        ),
        migrations.AlterField(
            model_name='parametreplateforme',
            name='paydunya_active',
            field=models.BooleanField(default=False, help_text='Activer le paiement en ligne par PayDunya (Mobile Money).'),
        ),
        migrations.AlterField(
            model_name='parametreplateforme',
            name='paydunya_master_key',
            field=models.CharField(blank=True, default='', help_text='Master key PayDunya (panel PayDunya)', max_length=200),
        ),
        migrations.AlterField(
            model_name='parametreplateforme',
            name='paydunya_private_key',
            field=models.CharField(blank=True, default='', help_text='Private key PayDunya', max_length=200),
        ),
    ]
