# Generated by Django 6.0.7 on 2026-07-20 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vente',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='vente',
            name='caissier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('ORANGE', 'Orange Money'), ('WAVE', 'Wave'), ('CARTE', 'Carte bancaire')], default='ESPECES', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vente',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='DetailVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ventes.vente')),
            ],
        ),
        migrations.DeleteModel(
            name='LigneVente',
        ),
    ]
