# Generated by Django 6.0.7 on 2026-08-01 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_alter_vente_options_rename_date_vente_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='annule_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Annulée le'),
        ),
        migrations.AddField(
            model_name='vente',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_annulees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vente',
            name='annulee',
            field=models.BooleanField(default=False, verbose_name='Vente annulée'),
        ),
    ]
