# Generated by Django 6.0.7 on 2026-08-04 16:17

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('ventes', '0003_vente_annule_le_vente_annule_par_vente_annulee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailvente',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='vente',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='detailvente',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='vente',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='detailvente',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant propriétaire de cette ligne', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.restaurant'),
        ),
        migrations.AddField(
            model_name='vente',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant propriétaire de cette ligne', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.restaurant'),
        ),
    ]
