# Generated by Django 6.0.7 on 2026-08-04 16:17

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'base_manager_name': 'all_objects', 'ordering': ['numero'], 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AlterModelManagers(
            name='table',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant propriétaire de cette ligne', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.restaurant'),
        ),
        migrations.AlterField(
            model_name='table',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('restaurant', 'numero'), name='unique_table_par_restaurant'),
        ),
    ]
