# Generated by Django 6.0.7 on 2026-07-21 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('commandes', '0001_initial'),
        ('menu', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table'),
        ),
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='lignecommande',
            old_name='prix_unitaire',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='adresse_livraison',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date_maj',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='livreur',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='telephone_livraison',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='type_commande',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='note',
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='serveur',
            field=models.ForeignKey(limit_choices_to={'role': 'SERVEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.produit'),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
