# Generated by Django 6.0.7 on 2026-07-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_alter_commande_table_alter_commande_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.TextField(blank=True, verbose_name='Adresse de livraison'),
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone_livraison',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone de livraison'),
        ),
    ]
