# Generated by Django 6.0.7 on 2026-07-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_adresse_livraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='adresse_livraison',
            field=models.TextField(blank=True, default='', verbose_name='Adresse de livraison'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='telephone_livraison',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone de livraison'),
        ),
    ]
