# Generated by Django 6.0.7 on 2026-07-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_alter_commande_adresse_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='type',
            field=models.CharField(choices=[('SUR_PLACE', 'Sur place'), ('LIVRAISON', 'Livraison')], default='SUR_PLACE', max_length=20, verbose_name='Type de commande'),
        ),
    ]
