# Generated by Django 6.0.7 on 2026-08-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_commande_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='type',
            field=models.CharField(choices=[('SUR_PLACE', 'Sur place'), ('A_EMPORTER', 'À emporter'), ('LIVRAISON', 'Livraison')], default='SUR_PLACE', max_length=20, verbose_name='Type de commande'),
        ),
    ]
