# Generated by Django 6.0.7 on 2026-07-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='RestaurantPro', max_length=100)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parametres/')),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('message_ticket', models.TextField(blank=True, default='Merci de votre visite et à bientôt !')),
            ],
        ),
    ]
