# Generated by Django 6.0.7 on 2026-08-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_remove_parametrerestaurant_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrerestaurant',
            name='url_site',
            field=models.URLField(blank=True, default='', help_text='URL publique du site, utilisée pour générer les QR codes des tables (ex: http://192.168.1.156:8000 ou http://monresto.com)', null=True),
        ),
    ]
