# Generated by Django 6.0.7 on 2026-08-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_parametrerestaurant_url_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrerestaurant',
            name='email_restaurant',
            field=models.EmailField(blank=True, default='', help_text='Adresse e-mail du restaurant (expéditeur des e-mails envoyés aux clients)', max_length=254),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='smtp_user',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
