# Generated by Django 6.0.7 on 2026-08-04 16:31

import apps.tenants.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_alter_parametrerestaurant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrerestaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenants.uploads.upload_restaurant),
        ),
    ]
