# Generated by Django 6.0.7 on 2026-08-04 16:17

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant propriétaire de cette ligne', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.restaurant'),
        ),
    ]
